### PR TITLE
OOP school library: refactor your code

### PR DESCRIPTION
**Pull request by mirouhml**
# Project requirements

- Make sure YAGNI, KISS, and DRY rules and Ruby style guide are respected.
- Follow SOLID principles.
- Pay special attention to the "Single-responsiblity Principle".
  - Make sure that the role of main.rb is only to start your code.
  - Extract some pieces of logic into separate class(es).

### CODE REVIEW

**Review by mikethreels — CHANGES_REQUESTED** [review]
Hi Team, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Required Changes ♻️
### Because no code was changed in your project I'm not able to leave any inline comments, any requirements will be in this comment. 
- [ ] in the below methods you are getting user input, printing to the console and processing the data this is not in line with the single responsibility rule, please have a look at [this article](https://github.com/microverseinc/curriculum-ruby/blob/main/oop/lessons/solid.md#best-practices-and-solid) for more info
https://github.com/mirouhml/ruby-oop-school-library/blob/409a5dd10d4814089a2b002cf7ad009cc7b3d91a/app.rb#L80-L109
https://github.com/mirouhml/ruby-oop-school-library/blob/409a5dd10d4814089a2b002cf7ad009cc7b3d91a/app.rb#L111-L120
https://github.com/mirouhml/ruby-oop-school-library/blob/409a5dd10d4814089a2b002cf7ad009cc7b3d91a/app.rb#L122-L146
https://github.com/mirouhml/ruby-oop-school-library/blob/409a5dd10d4814089a2b002cf7ad009cc7b3d91a/app.rb#L148-L169
please create separate methods for interactions with the customer and processing of the data.

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by mirouhml** [comment]
@mikethreels thanks for the review I will look into what you mentioned.

**Review by t-yanick — APPROVED** [review]
Hi @mikethreels , 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit:  
Congratulations! 🎉 

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by mirouhml** [comment]
@t-yanick Thanks for the approval.

**Pull request merged**
